// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QmlFormat
{
    internal sealed partial class Vsix
    {
        public const string Id = "QmlFormat.9850cb6c-8d26-476d-83f6-7841498fdc01";
        public const string Name = "QmlFormat";
        public const string Description = @"Format qml file using Qt qmlformat tool";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "rybcom";
        public const string Tags = "";
    }
}
